version: '3.8'

services:
  backend:
    image: cr.yandex/crpeb7h45g4a6gi4qeiu/backend:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=toddler_user
      - DB_PASSWORD=passpassik
    depends_on:
      - postgres

  frontend:
    image: cr.yandex/crpqkegfau1383imp6jn/frontend:latest
    ports:
      - "80:80"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: toddler_user
      POSTGRES_PASSWORD: passpassik
      POSTGRES_DB: toddler
    ports:
      - "5432:5432"
    volumes:
      - toddler_data:/var/lib/postgresql/data

volumes:
  toddler_data:
