spring:
  profiles:
    default: local
  liquibase:
    change-log: "classpath:/db/changelog/db.changelog-master.xml"
    enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/toddler
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mail:
    host: smtp.yandex.ru
    port: 465
    username: mikhailsosipatrov194@yandex.ru
    password: cwddqddkwhhogbsf
    protocol: smtps
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

  # Enable scheduling
  task:
    scheduling:
      enabled: true

application:
  file:
    upload-dir: /var/app/uploads
    access-url: http://localhost:8080/uploads/

