spring:
  profiles:
    default: local
  liquibase:
    change-log: "classpath:/db/changelog/db.changelog-master.xml"
    enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/toddler
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE

application:
  test: hello
